google/prefab

- docs/build-systems.md
- docs/index.md
tip.html is part of a theme that we're not using.
> Fix Jekyll pages.

- cli/src/test/kotlin/com/google/prefab/cli/NdkBuildPluginTest.kt
> Add missing header-only test to NdkBuildPluginTest.

- api/src/main/kotlin/com/google/prefab/api/Module.kt
The newest Kotlin Plugin knows that this is @NonNull.
/gcbrun
> Clean up warning.

- api/src/main/kotlin/com/google/prefab/api/Android.kt
> Provide useful toString for Android.

- api/src/test/kotlin/com/google/prefab/api/AndroidTest.kt
> Fix typo in test comment.

- api/src/main/kotlin/com/google/prefab/api/Package.kt
- api/src/main/kotlin/com/google/prefab/api/PackageMetadataV1.kt
- api/src/test/kotlin/com/google/prefab/api/PackageTest.kt
- cli/src/test/kotlin/com/google/prefab/cli/CMakePluginTest.kt
- cli/src/test/kotlin/com/google/prefab/cli/PackageTest.kt
- cli/src/test/resources/com/google/prefab/cli/packages/bad_package_version/modules/foo/module.json
- cli/src/test/resources/com/google/prefab/cli/packages/bad_package_version/package.json
- cli/src/test/resources/com/google/prefab/cli/packages/foo/package.json
- cli/src/test/resources/com/google/prefab/cli/packages/header_only/package.json
- cli/src/test/resources/com/google/prefab/cli/packages/qux/package.json
- cmake-plugin/src/main/kotlin/com/google/prefab/cmake/CMakePlugin.kt
- docs/index.md
Fixes https://github.com/google/prefab/issues/10
/gcbrun
> Support the CMake version file.

- api/src/main/kotlin/com/google/prefab/api/Android.kt
- api/src/main/kotlin/com/google/prefab/api/Module.kt
- api/src/main/kotlin/com/google/prefab/api/PlatformInterface.kt
- api/src/test/kotlin/com/google/prefab/api/AndroidTest.kt
- cli/src/test/kotlin/com/google/prefab/cli/ModuleTest.kt
- cli/src/test/resources/com/google/prefab/cli/packages/find_best_match/modules/byapi/libs/android.arm64-v8a-23/abi.json
- cli/src/test/resources/com/google/prefab/cli/packages/find_best_match/modules/byapi/libs/android.arm64-v8a-24/abi.json
- cli/src/test/resources/com/google/prefab/cli/packages/find_best_match/modules/byapi/libs/android.arm64-v8a-28/abi.json
- cli/src/test/resources/com/google/prefab/cli/packages/find_best_match/modules/byapi/module.json
- cli/src/test/resources/com/google/prefab/cli/packages/find_best_match/modules/byndk/libs/android.arm64-v8a-19/abi.json
- cli/src/test/resources/com/google/prefab/cli/packages/find_best_match/modules/byndk/libs/android.arm64-v8a-20/abi.json
- cli/src/test/resources/com/google/prefab/cli/packages/find_best_match/modules/byndk/libs/android.arm64-v8a-21/abi.json
- cli/src/test/resources/com/google/prefab/cli/packages/find_best_match/modules/byndk/module.json
- cli/src/test/resources/com/google/prefab/cli/packages/find_best_match/prefab.json
Fixes https://github.com/google/prefab/issues/8
/gcbrun
> Find the best match lib rather than first match.

- build.gradle.kts
We're not quite at 1.0 yet, but we should get something published to
Maven so the other tools using this have something to pull from.
/gcbrun
> Drop version back to 0.9.0.

- api/src/main/kotlin/com/google/prefab/api/Android.kt
- api/src/main/kotlin/com/google/prefab/api/Module.kt
- api/src/main/kotlin/com/google/prefab/api/PlatformInterface.kt
- api/src/test/kotlin/com/google/prefab/api/AndroidTest.kt
- cli/src/main/kotlin/com/google/prefab/cli/App.kt
- cli/src/main/kotlin/com/google/prefab/cli/Cli.kt
- cli/src/test/kotlin/com/google/prefab/cli/ModuleTest.kt
- cmake-plugin/src/main/kotlin/com/google/prefab/cmake/CMakePlugin.kt
- ndk-build-plugin/src/main/kotlin/com/google/prefab/ndkbuild/NdkBuildPlugin.kt
If no compatible library is found, print a list of all libraries tried
along with their reasons for rejection.
/gcbrun
> Show reasons for library rejection.

- build.gradle.kts
All the important TODOs are done and all our open bugs have been
fixed (once https://github.com/google/prefab/pull/32 is merged).
/gcbrun
> Bump to 1.0.

- cli/src/test/kotlin/com/google/prefab/cli/CMakePluginTest.kt
- cmake-plugin/src/main/kotlin/com/google/prefab/cmake/CMakePlugin.kt
Fixes https://github.com/google/prefab/issues/52
/gcbrun
> Fix static library export in cmake.

- docs/index.md
> Fix field name in module metadata docs.

- build.gradle.kts
> Update to Kotlin 1.3.61.

- .github/ISSUE_TEMPLATE/bug_report.md
GitHub interprets this as a todo list.
/gcbrun
> Remove checkboxes from bug template.

- .idea/codeStyles/Project.xml
- RELEASING.md
- scripts/release
- scripts/release.kts
> Turn the release process into a script.

- api/src/main/kotlin/com/google/prefab/api/Elf.kt
Fixes https://github.com/google/prefab/issues/70.
/gcbrun
> Fix misleading error message.

- api/src/main/kotlin/com/google/prefab/api/Android.kt
- api/src/main/kotlin/com/google/prefab/api/Package.kt
Fixes https://github.com/google/prefab/issues/79
/gcbrun
> Provide useful message for all require checks.

- api/src/main/kotlin/com/google/prefab/api/Android.kt
The pull-up done for the API level prior to the first supported API
level for the ABI is done silently, so users that aren't aware of this
behavior are likely to be confused by the apparent non-duplicates in
their duplicate lists. Add a note to the error message to make it
clear.
When we eventually break the schema we should just explicitly disallow
API levels that were never supported for the given ABI.
Fixes https://github.com/google/prefab/issues/100
> Add note for implicit API level in duplicates.

- cli/src/test/kotlin/com/google/prefab/cli/CMakePluginTest.kt
- cmake-plugin/src/main/kotlin/com/google/prefab/cmake/CMakePlugin.kt
https://github.com/google/prefab/issues/122
https://cmake.org/cmake/help/latest/policy/CMP0037.html
> Fix header only libraries in CMake.

- docs/index.md
Fixes https://github.com/google/prefab/issues/135.
> Update link to Studio docs.
