.cloudbuild/release.yaml, build.gradle.kts
Change the current version built by default to 1.0.0-SNAPSHOT and
configure a "release" task. The release task requires the tag name
that's passed to the project via CI, which will be used as the version
string for that build.
This also causes dokka to run. I'm not currently archiving those
results because I'm not sure about the best way to get those onto our
docs page yet, but that's something we should do.
=> Set up release build flow.

.idea/inspectionProfiles/Project_Default.xml
Keep requiring explicit types on public APIs to avoid accidental API
changes, but don't require it for private or internal APIs.
/gcbrun
=> Tone down type inference inspection.

cli/build.gradle.kts
Save users and AGP the trouble of finding all the other jars to put on
the classpath.
=> Make the CLI a fat jar.

api/src/main/kotlin/com/google/prefab/api/Android.kt, api/src/main/kotlin/com/google/prefab/api/PlatformInterface.kt, api/src/test/kotlin/com/google/prefab/api/AndroidTest.kt, cli/src/main/kotlin/com/google/prefab/cli/Cli.kt, cli/src/test/kotlin/com/google/prefab/cli/ArgParserTest.kt, cli/src/test/kotlin/com/google/prefab/cli/CMakePluginTest.kt, cli/src/test/kotlin/com/google/prefab/cli/EndToEndTest.kt, cli/src/test/kotlin/com/google/prefab/cli/ModuleTest.kt, cli/src/test/kotlin/com/google/prefab/cli/NdkBuildPluginTest.kt, cli/src/test/kotlin/com/google/prefab/cli/PackageTest.kt, cmake-plugin/src/main/kotlin/com/google/prefab/cmake/CMakePlugin.kt, docs/index.md
We can't do this in every case, since old NDKs didn't set the
appropriate value in their toolchain file, but use it where we can.
Fixes https://github.com/google/prefab/issues/11
/gcbrun
=> Use the architecture-specific layout for CMake.

api/src/main/kotlin/com/google/prefab/api/Package.kt
The Module constructor is passed a reference to the incompletely
constructed Package. This is probably a pattern we should avoid, but
for now fix the issue with the package name being null during module
construction.
/gcbrun
=> Fix initialization order in Package.

build.gradle.kts
This was the wrong group, and from a quick inspection of some other
Google POMs (protobuf and truth) we don't usually set this anyway.
/gcbrun
=> Remove the developers field from the POM.

api/src/main/kotlin/com/google/prefab/api/BuildSystemInterface.kt, cli/build.gradle.kts, cli/src/main/kotlin/com/google/prefab/cli/BuildSystemRegistry.kt, cli/src/main/kotlin/com/google/prefab/cli/Cli.kt, cli/src/test/kotlin/com/google/prefab/cli/ArgParserTest.kt, cmake-plugin/src/main/kotlin/com/google/prefab/cmake/CMakePlugin.kt, cmake-plugin/src/main/kotlin/com/google/prefab/cmake/CMakePluginProvider.kt, cmake-plugin/src/main/resources/META-INF/services/com.google.prefab.api.BuildSystemProvider, docs/build-systems.md, docs/index.md, ndk-build-plugin/src/main/kotlin/com/google/prefab/ndkbuild/NdkBuildPlugin.kt, ndk-build-plugin/src/main/kotlin/com/google/prefab/ndkbuild/NdkBuildPluginProvider.kt, ndk-build-plugin/src/main/resources/META-INF/services/com.google.prefab.api.BuildSystemProvider
Rather than having these be passed as `--plugin-path` on the
command-line, which requires more complicated testing and a separate
code path for built-in plugins as compared to user loaded, just load
all plugins available on the classpath, and load the default ndk-build
and CMake plugins that way rather than explicitly loading them.
Users that want to load their own plugins will need to modify the Java
command line to include their own plugin JARs in the classpath.
Fixes https://github.com/google/prefab/issues/22
=> Load build system plugins from the classpath.

RELEASING.md, build.gradle.kts, gradle.properties
I've added a doc (much of which can probably be distilled into a
script later on) and moved the configuration from the guts of the
build.gradle.kts into gradle.properties.
This is an alternative to https://github.com/google/prefab/pull/34.
/gcbrun
=> Refine the release process.

cli/src/main/resources/META-INF/services/com.google.prefab.api.BuildSystemProvider, cmake-plugin/src/main/resources/META-INF/services/com.google.prefab.api.BuildSystemProvider
The JAR was getting multiple entries for the same file which resulted
in only one plugin being visible. Ideally they would be merged, but
I'm not sure how to do that in Gradle, so for now just move the
service provider metadata into the CLI package since we don't need the
build plugins to work separately anyway.
=> Fix service definition in the CLI fat JAR.

api/build.gradle.kts, build.gradle.kts, cli/build.gradle.kts, cmake-plugin/build.gradle.kts, ndk-build-plugin/build.gradle.kts
These aren't tested to work if distributed separately of the CLI fat
JAR, so avoid publishing them until we need to.
=> Don't publish the ndk-build or CMake plugins.

api/build.gradle.kts, build.gradle.kts, cli/build.gradle.kts, cmake-plugin/build.gradle.kts, cmake-plugin/src/main/resources/META-INF/services/com.google.prefab.api.BuildSystemProvider, gradle.properties, ndk-build-plugin/build.gradle.kts, ndk-build-plugin/src/main/resources/META-INF/services/com.google.prefab.api.BuildSystemProvider
The way I'd previously done this left all of the dependencies stated
in the POM even though they were included in the JAR. The shadow
plugin appears to be quite widely used and does a better job of
building fat JARs.
This also conveniently deals with the merging of service files for us,
so I've reverted the changes in
https://github.com/google/prefab/pull/36 and used that instead, and
similarly merged our NOTICE files (they're all currently identical,
but this future-proofs it).
Since the two publication configurations have now diverged quite a
bit, I removed them from the common build.gradle.kts and defined each
in their own build files. The common components have been moved to
gradle properties.
/gcbrun
=> Use the shadow plugin to create the fat JAR.

cli/src/test/kotlin/com/google/prefab/cli/CMakePluginTest.kt, cli/src/test/kotlin/com/google/prefab/cli/NdkBuildPluginTest.kt, cmake-plugin/src/main/kotlin/com/google/prefab/cmake/CMakePlugin.kt, ndk-build-plugin/src/main/kotlin/com/google/prefab/ndkbuild/NdkBuildPlugin.kt
These were being emitted as unescaped backslash delimited paths. Both
ndk-build and CMake are fine with forward slash delimited paths (and
ndk-build prefers them), so emit those instead.
/gcbrun
=> Convert Windows paths in build files.

cli/src/test/kotlin/com/google/prefab/cli/CMakePluginTest.kt, cmake-plugin/src/main/kotlin/com/google/prefab/cmake/CMakePlugin.kt
If the system has a Find$DEP.cmake available, CMake might prefer that
definition to ours. It almost certainly won't contain libraries for
Android, and it may not even expose the same interface. It may not
necessarily find *any* libraries at all.
Enforce that a config-style package is loaded rather than the
module-style package (see
https://cmake.org/cmake/help/latest/command/find_package.html).
/gcbrun
=> Require config packages in CMake.

CHANGELOG.md, RELEASING.md
Merging the tags back into the master branch isn't useful since we
only take rebases anyway. Drop that part of the release process, and
make the changelog be something continuously updated in the tree
rather than something that only exists in release commits/branches.
/gcbrun
=> Update release process.

README.md
Related: https://github.com/google/prefab/issues/60
=> Add instructions for building CLI executable

api/src/main/kotlin/com/google/prefab/api/Android.kt, api/src/test/kotlin/com/google/prefab/api/AndroidTest.kt
https://docs.oracle.com/javase/10/docs/api/java/nio/file/FileSystem.html#getPathMatcher(java.lang.String)
> The * character matches zero or more characters of a name component
> **without crossing directory boundaries.**
/gcbrun
=> Fix path matcher in Android STL checker.

api/src/main/kotlin/com/google/prefab/api/Android.kt, docs/index.md, docs/platform-support.md
I've removed the TODO for the authoring guide. I don't think we can
usefully write an authoring guide that isn't Android specific beyond
what's already documented.
There are still TODOs to get the javadoc hosted somewhere, but I
haven't sorted that process out yet.
=> Fix most doc TODOs.

cli/src/test/kotlin/com/google/prefab/cli/CMakePluginTest.kt, cmake-plugin/src/main/kotlin/com/google/prefab/cmake/CMakePlugin.kt
https://cmake.org/cmake/help/latest/command/find_package.html says
that the config file can take two forms, <PackageName>Config.cmake or
<lower-case-package-name>-config.cmake. Right now we use the -config
form but don't transform the name to lower case.
Experimentally CMake uses the C locale for this, but the docs don't
take a stance (although it appears that anything outside
`[A-Za-z0-9_.:+-]+` isn't valid in a target name anyway), so just
avoid the problem altogether than use the untransformed name.
No test added because until we actually work a full end-to-end test
that actually runs CMake into our tests there isn't any useful test to
write here.
Fixes https://github.com/google/prefab/issues/98
=> Avoid CMake config file case issues.

api/src/main/kotlin/com/google/prefab/api/Module.kt, cli/src/main/kotlin/com/google/prefab/cli/App.kt, cli/src/main/kotlin/com/google/prefab/cli/Cli.kt, cli/src/test/kotlin/com/google/prefab/cli/CMakePluginTest.kt, cli/src/test/kotlin/com/google/prefab/cli/NdkBuildPluginTest.kt, cli/src/test/resources/com/google/prefab/cli/packages/static_and_shared/modules/foo/libs/android.shared/abi.json, cli/src/test/resources/com/google/prefab/cli/packages/static_and_shared/modules/foo_static/libs/android.static/abi.json, cli/src/test/resources/com/google/prefab/cli/packages/static_and_shared/modules/foo_static/module.json, cli/src/test/resources/com/google/prefab/cli/packages/static_and_shared/prefab.json, cmake-plugin/src/main/kotlin/com/google/prefab/cmake/CMakePlugin.kt, ndk-build-plugin/src/main/kotlin/com/google/prefab/ndkbuild/NdkBuildPlugin.kt
A package might contain modules that are only compatible with some
configurations. The motivating example of this is where a package
contains a shared library that uses c++_shared, but the user is using
c++_static. In this case, the one incompatible module shouldn't
preclude the user from using other modules in the package.
I don't really like the implementation here. The decision of whether
incompatible modules should be skipped or cause an error should not be
made by each build system plugin, but it'll take some rearranging of
the build system interface API to make that the CLI's responsibility.
I'm making this quick fix for our in-tree build systems for now, and
will the organization when we have more changes that justify a major
release.
=> Skip modules that have no match.

gradle.properties
Forgot to upload the similar change for 1.1.0. All the snapshot builds
after 1.1.0 (which was actually only one build) were 1.0.0-SNAPSHOT
instead of 1.1.0-SNAPSHOT.
=> Bump next version to 1.2.0.

cli/src/test/kotlin/com/google/prefab/cli/CMakePluginTest.kt, cmake-plugin/src/main/kotlin/com/google/prefab/cmake/CMakePlugin.kt
Protects against duplicate definition errors when a package is
included multiple times in CMake.
No change needed for ndk-build because it handles this internally.
Fixes https://github.com/google/prefab/issues/128
=> Add include guards for CMake targets.

build.gradle.kts
I think this is only fixing the declaration in the gradle module
properties since the Kotlin compiler was already configured for 1.8
and we don't (directly) use any Java, but the gradle module properties
certainly think we're using Java 11 without this.
=> Fix Java 8 compatibility.

docs/index.md
Replacing "the" with "that" in "Prefab is a command line tool the operates".
=> Correct Type In Usage

docs/example-workflow.md
It seems jekyll markdown URL references are case sensitive, although
GitHub is fine with this.
=> Fix links in the non-AGP workflow doc.

build.gradle.kts
We don't need (or want) JDK 8, we just need the output to be compatible with JRE 8 (though even that's debatable and we should figure out what a reasonable minimum Java version is these days).
Fixes https://github.com/google/prefab/issues/166.
=> Fix Java toolchain requirement.

cli/src/test/kotlin/com/google/prefab/cli/PackageTest.kt
Windows fails to clone the repo because of the directory name "android.". To make it possible for Windows to clone the repo, this change renames "android." to "android" and then renames the directory before running the test.
To avoid polluting the resource directory, a copy of the tests data is made in a temp directory.
=> Fix "Windows can't clone repo"

cli/build.gradle.kts
https://github.com/johnrengelman/shadow/issues/860 says this is a bug in shadow 8.1.1. Revert to 8.1.0 until there's a fix available.
=> Fix missing -all JAR suffix.
